### ISSUE TITLE
"Create a new domain" not working in Service Provider View

### ISSUE THREAD

**Issue by Crixu** [plesk/ext-welcome-business#1]
## Requirements:
- Plesk with no added domain
- Business Welcome Extension Version 1.0.1-3

## Behaviour
On the initial screen of the extension if you click on the "Create a new domain" link you get redirected to the same page again.

**Comment by Kubik-Rubik** [comment]
Fixed with https://github.com/plesk/ext-welcome-business/commit/704bdec4f4dbb8df683fc56bc70202b50bbcff5d
